.travis.yml
MariaDB.xs
dbdimp.c
dbdimp.h
t/rt118977-zerofill.t

Main change is usage public API functions of C library instead of accessing private structure members of C library. This fixes compatibility with new versions of MariaDB C client library.

Better compatibility with MariaDB

---

lib/DBD/MariaDB.pm

Several references to DBD::MariaDB that are actually referring to DBD::mysql. Also you may want to add a section to AUTHORS regarding the authorship of this fork.

Correct references to DBD::mysql in docs

---

lib/DBD/MariaDB.pm

See: https://github.com/perl5-dbi/dbi/pull/56
See: https://www.nntp.perl.org/group/perl.dbi.announce/2018/01/msg497.html

DBD::MariaDB driver was registered into DBI in version 1.640

---

dbdimp.c
dbdimp.h

API function dbd_db_login6_sv() is available since DBI 1.608 and
DBD::MariaDB already depends on DBI 1.609.
This change fixes compile warning: variable 'attribs' set but not used.

Use dbd_db_login6_sv() instead of dbd_db_login()

---

t/40types.t

Do not compare floating point values for equality. Rather use cmp_deeply
and num() from Test::Deep with epsilon precision.
Fixes: https://github.com/gooddata/DBD-MariaDB/issues/13

Fix test t/40types.t

---

.travis.yml
Makefile.PL
dbdimp.c
dbdimp.h
lib/DBD/MariaDB.pm
t/70takeimp.t
t/71impdata.t
t/89async-method-check.t

DBD::MariaDB already uses API of 1.608 version, therefore this is correct
minimal required version. Minimal required Perl version is 5.8.1.
Remove also checks for DBI version 1.42 and 1.607.
Those checks are not needed anymore as minimal required version is 1.608.

Set minimal DBI version and remove useless checks

---

dbdimp.c
lib/DBD/MariaDB.pm

Some arguments (host, user, passwd, db, port or unix_socket) passed to
mysql_real_connect() have different meaning when are NULL and when are "".
But DBD::MariaDB currently converts everything to nul term strings which
disallow usage of NULL arguments.
This commit fixes it by mapping Perl's undef to C's NULL and Perl's empty
string to C's "".
Also hide passwords in trace logs.
See: https://dev.mysql.com/doc/refman/en/mysql-real-connect.html
See: https://mariadb.com/kb/en/library/mysql_real_connect/
Fixes: https://github.com/perl5-dbi/DBD-mysql/issues/167
Fixes: https://rt.cpan.org/Public/Bug/Display.html?id=108650

Distinguish between NULL and "" and hide passwords in trace logs

---

.travis.yml
MANIFEST
Makefile.PL
t/40types.t
t/80procs.t
t/81procs.t
t/lib.pl
testrules.yml

Use testrules.yml definition file for TAP::Harness which is used by prove
and also by ExtUtils::MakeMaker's make test. All tests except those which
initialize database can be run in parallel and in any order.

Allow to run tests in parallel via make test

---

dbdimp.c
dbdimp.h
t/40bindparam2.t
t/40server_prepare_crash.t
t/43count_params.t
t/55utf8.t
t/rt83494-quotes-comments.t

DBI checks number of parameters when they are passed via execute() method,
not via bind_param(). Therefore DBD::MariaDB driver needs to check for
number of bind parameters in other cases.
Prior this change, DBD::MariaDB passed empty allocated memory for every
parameter which was not correctly bound.

Check that correct number of bind parameters were supplied

---

MANIFEST
dbdimp.c
t/25lockunlock.t
t/35prepare.t
t/40numrows.t
t/40sth_attr.t
t/56connattr.t

Retrieving $sth attributes after $sth->fetchall* call was not possible. DBI
just threw following error:
DBD::MariaDB::st FETCH failed: statement contains no result
This change fixes problem by letting $sth handle active even after last row
was fetched. When $sth is not active then fetching $sth attributes is not
possible.

Fix retrieving $sth attributes after $sth->fetchall* call

---

t/41int_min_max.t

Remove code which hides all warnings and fix wrong test code. Pattern
ok{...} was interpreted as a hash and throw followed warnings:
Odd number of elements in anonymous hash at t/41int_min_max.t line 55.
Odd number of elements in anonymous hash at t/41int_min_max.t line 68.
Odd number of elements in anonymous hash at t/41int_min_max.t line 83.
Odd number of elements in anonymous hash at t/41int_min_max.t line 87.
Odd number of elements in anonymous hash at t/41int_min_max.t line 103.
Odd number of elements in anonymous hash at t/41int_min_max.t line 107.
But because warnings were silenced tests always passed. This change also
fixes test code and call function ok() properly.

Fix wrong code in test t/41int_min_max.t

---

t/80procs.t
t/81procs.t
t/lib.pl

PROCEDURE statements do not work without this table so affected tests will
fail with error:
DBD::MariaDB::db do failed: Table 'mysql.proc' doesn't exist at t/80procs.t line 39.
DBD::MariaDB::db do failed: Table 'mysql.proc' doesn't exist at t/81procs.t line 39.

Skip tests t/80procs.t and t/81procs.t when table mysql.proc doesn't exist

---

lib/DBD/MariaDB.pm
t/05dbcreate.t
t/41int_min_max.t
t/55utf8_jp.t
t/90utf8_params.t
t/rt61849-bind-param-buffer-overflow.t
t/rt75353-innodb-lock-timeout.t

For tests in more cases it can be replaced by DBI's errstr function.

Remove usage of $@ in tests where possible

---

Makefile.PL
MariaDB.xs
dbdimp.c
dbdimp.h

* Use dbd_st_execute_iv API when available
* Store result of mysql_get_client_version() and mysql_get_server_version() into unsigned long variable
* Fix and simplify code which uses number of returned or affected rows

Fix statement execute function

---

MariaDB.xs
dbdimp.c
dbdimp.h
t/rt91715.t

Use bool type for perl API code and my_bool for mysql API code, instead of
int or char. And use only FALSE/TRUE boolean constant instead of false/true
or 0/1 as FALSE/TRUE is expected by both perl and mysql API. For creating
perl boolean scalars use boolSV() function instead of long newSViv wrapper.

 Fix usage of boolean variables

---

MariaDB.xs
dbdimp.c

Those functions already take non-negative integer passed via signed integer
type. Also such casting was useless as it was automatically implicit.

Remove useless integer casting in Newz function calls

---

dbdimp.c

Those formats do not have to be supported by PerlIO_printf(). Therefore
replace them by string ("%s") or scalar ("%" SVf) formats.

Remove %llu and %lld from PerlIO_printf

---

dbdimp.c
dbdimp.h

Different compile warnings are produced by perl and gcc on RHEL6, RHEL7 and Debian 9. Fix/workaround all of them.

Fix compile warnings

---

dbdimp.c

Update #ifdef check for mysql_options4 and MYSQL_OPT_CONNECT_ATTR_ADD. They
are supported also by MariaDB client libraries.

Update support for mariadb_conn_attrs attribute

---

dbdimp.c
t/40server_prepare_crash.t

Fixes commit e29584871e9fcae6ff0338a48bb76ad988e70ab1 as some MySQL and
some MariaDB clients set unitilized or zero value for name_length and
table_length of prepared statements. Problem affects all MySQL client
versions prior to version 5.5.0; all MariaDB clients 10.2.4 and new; and
all MariaDB Connector/C clients.
When using affected client, calculate length manually via strlen() to
prevent using uninitialized or zero length value.
Crash happen when prepared statements are enabled and calling some complex
DBI function like $dbh->selectall_hashref().

Fix crashing with older MySQL and new MariaDB clients when prepared statements are used

---

dbdimp.h
lib/DBD/MariaDB.pm
lib/DBD/MariaDB/INSTALL.pod
t/92ssl_connection.t

* Fix version checks for library versions with SSL vulnerabilities (CVE-2015-3152, CVE-2017-3305, CVE-2018-2767)
* Fix test t/92ssl_connection.t, do not check for SSL when SSL is optional
* Remove information about SSL compile time option

CVE-2018-2767: Handle SSL problems of MySQL and MariaDB clients

---

dbdimp.c

Set nul term byte explicitly. Older perl versions prior to 5.16 have
problem when string in SvPVX() is not explicitly terminated by nul byte
even length of the string is correctly set by SvCUR_set() call.
This memory problem was detected by valgrind error:
Conditional jump or move depends on uninitialised value(s)

In method data_sources() fix reading from uninitialized memory

---

.travis.yml
appveyor.yml
dbdimp.c
t/40server_prepare_crash.t
t/cve-2017-3302.t

Ensure that there is no unprepared, but allocated MYSQL_STMT structure which can cause memory corruption and crash in MySQL and MariaDB clients affected by CVE 2017-3302.
And also prevent another two NULL pointer dereference in DBD::MariaDB code.

Try to mitigate CVE 2017-3302 libmysqlclient.so defect of leaking dangling pointers

---

MANIFEST
dbdimp.c
dbdimp.h
t/13disconnect.t

Shutdown client library via mysql_server_end() only when unloading DBI
driver due to bugs in both MySQL and MariaDB client libraries.
See: https://jira.mariadb.org/browse/CONC-336

Implement disconnect_all method

---

dbdimp.c
dbdimp.h
t/70takeimp.t

Track all take_imp_data() calls and store MYSQL* pointers into global
driver array. When a new DBI connection with imp_data is going to be
established, check that imp_data comes from tracked take_imp_data() call
and that MYSQL* pointer inside is valid. After reusing imp_data remove
MYSQL* pointer from global driver array, so it cannot be again reused.
When disconnect_all() is called, close also tracked connections from
take_imp_data() which were not yet reused. This fixes memory leaks when
caller of take_imp_data() discard taken data and not reuse them. Also it
ensure that these connections are properly closed prior perl process
finished.
This change also fixes segfaults and memory corruptions when same taken
imp_data are passed to the two different connections. Now instead of
segfault it …

Store all taken MYSQL* connections and close them in disconnect_all()

---

dbdimp.c

Each bind parameter needs buffer at least of size 2*len (worst case
every character is escaped) plus 2 bytes for quotes. Final length is then
increased by one for nul term byte.
Also remove misleading/wrong comment about *2 as it does not make sense.

Fix calculation of buffer size for client side placeholder replacing

---

Makefile.PL
dbdimp.c

Disallow DBI connection when using wrong combination of mariadb_socket, host and port parameters

Fix generating dsn for tests and check for errors in dsn

---

MariaDB.xs
dbdimp.c
dbdimp.h
t/31insertid.t

MySQL 5.7 below 5.7.18 and MySQL 8.0.0 are affected by Bug #78778.
mysql_insert_id() is reset to 0 after performing SELECT operation.
As a workaround prior to issuing mysql query we store value of last insert
id. If query returns result set then we know that it was SELECT operation
and so after that we restore previous value of last insert id.
MySQL 5.7, MySQL 8.0, MySQL Connector/C 6.1.5 and higher are affected by
Bug #89139. mysql_insert_id() is reset to 0 after calling mysql_ping() C
function.
As a workaround prior to calling mysql_ping() function we store value of
last insert id. After function finish we restore previous value of last
insert id.
DBD::MariaDB had already second workaround but with wrong version check.
This commit therefore fix version check for second workaround and …

Fix last insert id workaround for MySQL 5.7 and 8.0 client versions

---

MANIFEST
dbdimp.c
t/45bind_no_backslash_escapes.t

MySQL client in version 5.7.6 changed API of the mysql_real_escape_string()
function in backward incompatible way. When SQL mode NO_BACKSLASH_ESCAPES
is active then this function returns value ULONG_MAX. When this number is
added to string pointer it effectively means subtraction by one. So it
removes last added character from string and totally breaks quoting.
New function mysql_real_escape_string_quote() which is available only in
MySQL client (since version 5.7.6) with passing '\\'' to the last argument
does the same thing as older versions of mysql_real_escape_string() used to
do.
Fixes: https://github.com/perl5-dbi/DBD-mysql/issues/221
See: https://stackoverflow.com/a/50933703/9963391

Fix placeholders replacement for MySQL client version >= 5.7.6

---

t/00base.t
t/05dbcreate.t
t/lib.pl

Without it some tests are failing on strange errors:
Use of uninitialized value $test_db in concatenation (.) or string at t/05dbcreate.t line 59.
Use of uninitialized value $test_db in concatenation (.) or string at t/05dbcreate.t line 73.
Use of uninitialized value $test_db in concatenation (.) or string at t/11data_sources.t line 29.
DBD::MariaDB::db prepare failed: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 at t/cve-2017-3302.t line 16.
This problem found by Debian Perl Group.

Fix parsing $test_dsn and ensure that it is always filled

---

Makefile.PL

Local UNIX socket and TCP host/port cannot be used together.
Also ensure that command line or ENV options can correctly override already
cached values.

Add sanity check for Makefile.PL --testsocket and --testhost

---

.travis.yml

MySQL::Sandbox uses different options for initialization database server and
for running database server.

Disable Native Linux asynchronous I/O subsystem on Travis also when initializing database

---

MariaDB.xs
dbdimp.c

Use only Perl's alloc/free functions. Perl redefines C library alloc
functions (malloc, realloc, free) to its own memory allocation and
therefore it is not safe to use C library functions which allocate memory.
Perl doesn't redefine calloc() so its usage is not safe as far as it
allocates using C library memory management but frees with Perl's.
See also: https://github.com/gooddata/DBD-MariaDB/issues/91

Fix allocating and releasing memory

---

dbdimp.c
dbdimp.h
t/45bind_no_backslash_escapes.t

When MySQL client library version differs from MySQL/MariaDB server version
and sql_mode is NO_BACKSLASH_ESCAPES then mysql_real_escape_string() does
not have to work.
As a workaround use mysql_hex_string() for escaping placeholders as this
function does not produce any backslashes or quotes characters. So it does
not conflict with NO_BACKSLASH_ESCAPES.

Fix escaping placeholders when sql_mode is NO_BACKSLASH_ESCAPES

---

dbdimp.c
lib/DBD/MariaDB.pod

Zero value means infinite timeout.
Also allow to set read and write timeout also for broken MariaDB Connector/C clients. Zero value (=infinite) value is simulated by maximal timeout value in those broken clients.

Allow to set zero timeouts and allow to set timeouts also for broken clients

---

Makefile.PL

This ensures that test suite finishes in finite time and does not freeze
when being run against broken database server.
Smaller timeouts (like 30 seconds) are not enough as sometimes CREATE TABLE
on Travis causes disconnect.

Set read, write and connect timeout for tests to 120 seconds

---

dbdimp.c
t/31insertid.t

MySQL 5.7 below 5.7.18 and MySQL 8.0.0 are affected by Bug #78778.
mysql_insert_id() is reset to 0 after performing SELECT operation.
This applies also for execution of prepared SELECT statement.
Fixes: 61dfddbf48b9c52fe06f5c3a6ba3840dc34c202e
See: https://bugs.mysql.com/bug.php?id=78778

Fix last insert id workaround also for prepared statements

---

dbdimp.c
t/05dbcreate.t
t/lib.pl

And for utf8 charset use utf8_unicode_ci collation.
Collation utf8mb4_unicode_ci is according to the Unicode 4.0.0 standard.
Collation utf8mb4_general_ci is broken UTF-8 collation. Due to historic
reasons utf8mb4_general_ci is default session collation.
This changes makes DBD::MariaDB more Unicode friendly as it avoids using
broken utf8mb4_general_ci collation.

Set default session collation to utf8mb4_unicode_ci

---

lib/DBD/MariaDB.pm

Without this change calling
$ perl -MDBI -e 'DBI->data_sources("MariaDB")'
cause following error:
Can't use an undefined value as a HASH reference

Allow to call DBI's method data_sources without second argument

---

dbdimp.c
t/40types.t

Use newSViv() for creating scalar from signed integer value. This fixes
underflow of negative DBI SQL data types for $sth->{TYPE} attribute.
Fixes: https://github.com/gooddata/DBD-MariaDB/issues/109

DBI SQL data type is signed integer value

---

t/rt88006-bit-prepare.t

DbiTestConnect calls "plan skip_all" when connection to database cannot be
established. And calling "plan" in the middle of test cause TAP errors.

Do not call plan in the middle of test t/rt88006-bit-prepare.t

---

MariaDB.xs
dbdimp.c
dbdimp.h
t/31insertid.t
t/76multi_statement.t

Some MySQL client versions have broken mysql_insert_id() function. Return
value of that function is reset to zero after calling mysql_ping() function
or after issuing SQL query which receive result set.
Seems that MySQL bug #89139 is not going to be fixed, but rather
documentation was changed about this "unexpected" behavior.
So instead of trying to detect which version of MySQL client is broken and
trying to workaround it by updating internal structure, call function
mysql_insert_id() only at time when it returns correct value and then store
it into dbh cache. On subsequent access just read cached value.
With this solution there is no needed to have tons of #ifdefs and cache is
used for all versions of MySQL and MariaDB clients.
See: https://bugs.mysql.com/bug.php?id=89139
See: …

Simplify workaround for MySQL clients with broken mysql_insert_id()

---

dbdimp.c
dbdimp.h

* Fix overflow in mariadb_thread_id and mariadb_warning_count attributes
* Do not export mariadb_st_internal_execute* functions

Fix overflow in attributes and do not export local functions

---

Changes
MANIFEST
Makefile.PL
MariaDB.xs
lib/DBD/MariaDB.pm
t/93net_ssleay.t

MariaDB deinitialize OpenSSL library in mysql_server_end() function.
Therefore Net::SSLeay stopped working after closing all DBD::MariaDB
handles. For disabling deinitialization of OpenSSL it is needed to set
global variable mariadb_deinitialize_ssl to zero.
Fixes: https://github.com/gooddata/DBD-MariaDB/issues/119

Fix breakage of Net::SSLeay / OpenSSL library after DBI disconnect

---

Makefile.PL
MariaDB.xs
dbdimp.c

Add configure check if mysql_server_end() deinitialize OpenSSL library
functions. And based on its result and presence of mariadb_deinitialize_ssl
variable ensure that mysql_server_end() is called only if it is safe.
Fixes: https://github.com/gooddata/DBD-MariaDB/issues/119
Fixes: https://www.cpantesters.org/cpan/report/116a074e-1a25-11e9-b285-f2255a3692e6

More robust solution to prevent deinitializing OpenSSL functions

---

socket.c

For using select() function on POSIX systems it is needed to include more
header files.
Fixes: 5034cd71c2179fc166bc55fd5633d8a3f02fced2

Fix compilation on OpenBSD and HP-UX

---

MariaDB.xs
dbdimp.c
t/35prepare.t
t/40numrows.t
t/76multi_statement.t

Method $sth->rows should return -1 when number of rows is unknown or when
some error occurred. Before this change method $sth->rows returned
18446744073709551615 (2^64-1) or 0. Now -1.
Fixes: https://github.com/jhthorsen/mojo-mysql/pull/47#issuecomment-460202982
Fixes: aed157b4c56ee12cd40b23d2c9a3f514cca4d455

Fix return value of $sth->rows when error occurred

---

MANIFEST
dbdimp.c
dbdimp.h
t/14destruct.t

During global destruction phase ChildHandles DBI attribute may be already
released or children can be undefs due to weakrefs.
So instead of relaying on ChildHandles, maintain own double linked list of
all imp_dbh structures with active MYSQL connection. This does not use any
Perl data structures so they are available at any time, including global
destruction phase.
Fixes: https://github.com/jhthorsen/mojo-mysql/pull/47#issuecomment-460202982
Fixes: 17d5aa04a96ec2654d20f70e2cc5862deeb4d953

Fix disconnect_all() method to work also during global destruction phase

---

dbdimp.c
t/35prepare.t

Function mariadb_st_execute_iv() did not reset current row, so next
mariadb_st_fetch() function call returned nothing if previously all data
were already fetched.
Now execute() reset current row to first one so fetch function starts
fetching from beginning.
This fixes usage of $dbh->prepare_cached() method, specially in
construction like this: $dbh->selectcol_arrayref($dbh->prepare_cached(...))
Fixes: 4f47a063f6c9fd89d709508022092965c29716df

Fix fetching rows after calling $sth->execute() second time

---

t/14destruct.t

skip_all doesn't skip assertions in the END block.

Skip tests in the END block explicitely

---

dbdimp.h

This reverts commit 5f3272e5dcd26eda3b4c6f0b6b00c00665953ff2.
MySQL bug #93276 is not fixed in 8.0.15 yet.
Fixes: https://github.com/gooddata/DBD-MariaDB/issues/137
See: https://bugs.mysql.com/bug.php?id=93276

Revert "MySQL bug #93276 is fixed in 8.0.15"

---

dbdimp.c

Fixes:
* Add a missing break to 'MYSQL_TYPE_NULL' case in mariadb_st_describe()
* Signal error if mariadb_db_async_result() in mariadb_st_finish() fails
___
@jplesnik: Could you please review/verify that fixes in this pull request for your reported issues are OK?

Fix #162 and #163

---

.github/workflows/ci.yaml
MANIFEST.SKIP
README.pod
dbdimp.c
dbdimp.h
t/00base.t

Copy old Travis CI script and rewrite it to Github Actions.
Fix also checks for older MariaDB versions in driver code because Github Actions CI tests were failing.

Add Github Actions CI 

---

MANIFEST
MariaDB.xs
dbdimp.c
dbdimp.h
lib/DBD/MariaDB.pod
t/78use_result.t

Problems with mariadb_use_result attribute were reported in issue https://github.com/perl5-dbi/DBD-MariaDB/issues/173
This pull request fixes mariadb_use_result attribute also when it is used together with mariadb_multi_statements=1 or mariadb_async=1 option.
Fixes: https://github.com/perl5-dbi/DBD-MariaDB/issues/173

Fix mariadb_use_result attribute

---

.github/workflows/ci.yaml

Package libssl1.0.0_1.0.2n-1ubuntu5.11_amd64.deb with minor version 11 disappeared from the Ubuntu archive.
So use package libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb without minor version which is still in Ubuntu archive.

Fix libssl1 package dependency in Github Actions CI

---

MANIFEST
dbdimp.c
dbdimp.h
t/15reconnect.t
t/18begin_work_without_raise_error.t
t/lib.pl

This is expected by DBI for correct error propagation of AutoCommit and begin_work().
See: https://github.com/perl5-dbi/dbi/issues/104

Croaks when changing AutoCommit attribute fails

---

t/25lockunlock.t
t/35limit.t
t/35prepare.t
t/40listfields.t
t/40nulls_prepare.t
t/40server_prepare_error.t
t/41bindparam.t
t/50commit.t
t/55utf8.t
t/55utf8_jp.t
t/55utf8mb4.t
t/65segfault.t
t/87async.t
t/88async-multi-stmts.t
t/89async-method-check.t
t/90utf8_params.t
t/91errcheck.t
t/rt25389-bin-case.t
t/rt88006-bit-prepare.t

* Use connection_id() test helper function in t/65segfault.t test
* Fix checking for errors in tests
* Remove useless call of die in tests where RaiseError is enabled
* Fix resetting warning handler to default in t/55utf8_jp.t test

Various fixes for tests

---

.github/workflows/ci.yaml
Makefile.PL
dbdimp.c
dbdimp.h
lib/DBD/MariaDB.pod
lib/DBD/MariaDB/INSTALL.pod
t/76multi_statement.t

* Allow to modify `$dbh->{mariadb_multi_statements}` also after connection to server was established
* Allow to specify `mariadb_auth_plugin` connection attribute

Improvements for database handle and connection attributes

---

.github/workflows/ci.yaml
dbdimp.c
dbdimp.h
t/40server_prepare.t
t/rt122541-decimals.t
t/rt85919-fetch-lost-connection.t

* Add new versions for testing on Github Actions CI
* Do not use MYSQL_OPT_RECONNECT for MySQL 8.0.34+ clients
* MySQL 8.0.20 client library has fixed reinitialization bug
* Fix MariaDB server version check in t/40server_prepare.t test
* Skip t/rt122541-decimals.t test for MySQL 8.0.22+ server versions
* Add new DECIMAL testcase into t/rt122541-decimals.t
* accept 4031 as a valid return code when connection closed

Fix support for MySQL 8.0

---

t/35limit.t

Tests are modified from the pull request https://github.com/perl5-dbi/DBD-mysql/pull/349 done by kebhr.

Add more tests for LIMIT keyword

---

MANIFEST
t/40blobslarge.t

Add test for large binary BLOB inserting with prepared statement and large Gzip binary as parameter.

Add test for large BLOB with parameter

---

dbdimp.c
t/35limit.t

Stop parsing a column named "limits" as the LIMIT keyword

---

dbdimp.c
t/13disconnect.t

Do not call mariadb_db_reconnect() during changing $dbh attributes unless needed

---

dbdimp.c

MariaDB and MySQL client libraries on Windows return zero value in my_socket type when connection to server is not of socket type.
Zero value may be interpreted as file descriptor for stdin, so skip processing of the zero value in socket related functions.

On Windows do not take WINAPI HANDLE of non-socket connections
